enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
logo: g2it_logo_lg.png
favicon: favicon.png
favicon_apple: apple-icon.png
favicon_72: apple-icon-72x72.png
favicon_144: apple-touch-icon-114x114.png
short_description: 'Our focus is to deliver high quality IT solutions, on time, every time. Our aim is to make your IT systems work for you, so that you can focus your energy where it is most needed...'
communications:
  headline: 'IT Services'
  items:
    -
      content: '1300 325 487'
    -
      content: info@g2it.com.au
    -
      content: '08 9335 5478'
  hotline: '1300 325 487'
  email: info@g2it.com.au
  phone: null
locations:
  headline: Locations
  items:
    -
      name: 'Perth Office'
      address: 'Unit 3 / 16 Mews Road, <br>Fremantle WA 6160'
    -
      name: 'Esperance Office'
      address: 'Unit 2 / 58 Windich Street,<br>Esperance WA 6450'
info:
  headline: 'Additional Info'
  items:
    -
      label: Disclaimer
      url: /disclaimer
    -
      label: Privacy
      url: /privacy
    -
      label: 'Client Login'
      url: 'https://cw.g2it.com.au/support'
    -
      label: 'Remote Support'
      url: 'https://g2it.screenconnect.com/'
    -
      label: 'Book Appointment'
      url: 'https://outlook.office365.com/owa/calendar/G2IT1@g2it.com.au/bookings/'
copyright: '&copy; All rights reserved.'
navigation:
  -
    url: /home
    menu: null
  -
    url: '#'
    menu: 'About us'
    children:
      -
        url: /who-we-are
      -
        url: /who-we-are/faq
  -
    url: /our-services
    menu: null
    children:
      -
        url: /our-services
      -
        url: /our-services/cloud-services-fremantle
      -
        url: /our-services/virtualisation-solutions
      -
        url: /our-services/it-suppport
      -
        url: /our-services/managed-it-services
      -
        url: /our-services/robo-it-support-perth
      -
        url: /our-services/backup-recovery-services-fremantle
      -
        url: /our-services/network-and-security-assessments
      -
        url: /our-services/cyber-security
      -
        url: /our-services/it-maintenance-perth
      -
        url: /our-services/it-project-management-perth
      -
        url: /our-services/strategy-and-planning
      -
        url: /our-services/voip-phone-systems-perth
      -
        url: /our-services/commercial-wifi-wireless-networks-perth
      -
        url: /our-services/lexmark-printer-servicing-fremantle
      -
        url: /our-services/it-procurement-perth
  -
    url: /our-people
    menu: null
  -
    url: /testimonials
    menu: null
  -
    url: /our-partners
    menu: null
  -
    url: /blog
    menu: Blog
  -
    url: /contact-us
    menu: null
facebook: 'https://www.facebook.com/G2ITAustralia/'
linkedin: 'https://www.linkedin.com/company/14527738/'
phone: '1300325487'
popup:
  title: 'G2IT in Esperance '
  content: "Our office in **_Esperance_** <br> \nis operating **_by appointment only_** <br>\nuntil further notice. \n\n<br>\nPlease call <a href=\"tel:1300325487\">1300 325 487</a>, <br>\nsend an [email](https://www.g2it.com.au/contact-us), <br>\nor book <a href=\"/tools/book-appointment\">**book an appointment.**</a>\n</div>\n\n"
  show: hide
icons:
  icon_1: null
  icon_1_alt: null
  icon_2: null
  icon_2_alt: null
topbar:
  button_label: Tools
  button_url: '#'
  tools_page: /tools
pay_invoice_page: /home
