title: 'G2IT - IT Support & IT Services in Fremantle, Esperance, Perth'
default_lang: en
author:
  name: 'G2 IT'
  email: info@g2it.com.au
taxonomies:
  - category
  - tag
metadata:
  description: 'Our focus is to deliver high quality IT solutions, on time, every time. Our aim is to make your IT systems work for you, so that you can focus your energy where it is most needed'
  title: 'G2IT - IT Support Fremantle, Esperance & Perth'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
