title: Services
'@extends': default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.view_button:
              type: text
              label: View button
            